echo circuit5M
wget https://sparse.tamu.edu/MM/Freescale/circuit5M.tar.gz
echo audikw_1
wget https://sparse.tamu.edu/MM/GHS_psdef/audikw_1.tar.gz
echo Bump_2911
wget https://sparse.tamu.edu/MM/Janna/Bump_2911.tar.gz
echo Queen_4147
wget https://sparse.tamu.edu/MM/Janna/Queen_4147.tar.gz
echo kron_g500-logn21
wget https://sparse.tamu.edu/MM/DIMACS10/kron_g500-logn21.tar.gz
echo hollywood-2009
wget https://sparse.tamu.edu/MM/LAW/hollywood-2009.tar.gz
echo rgg_n_2_24_s0
wget https://sparse.tamu.edu/MM/DIMACS10/rgg_n_2_24_s0.tar.gz
echo europe_osm
wget https://sparse.tamu.edu/MM/DIMACS10/europe_osm.tar.gz
echo indochina-2004
wget https://sparse.tamu.edu/MM/LAW/indochina-2004.tar.gz
echo soc-LiveJournal1
wget https://sparse.tamu.edu/MM/SNAP/soc-LiveJournal1.tar.gz

